name: Clean-Branches

on:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'

# Define jobs to clean old stale branches
jobs:
    clean-stale-branches:
        runs-on: ubuntu-latest
        steps:
        - name: Clean stale branches
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
#           Dry run remove branches that have been merged into main or develop
#           and have not been updated in the last 30 days, and remove branches
          run: |
#            Fetch branches to be deleted and save them in a variable
            branches=$(git branch --merged main | grep -v main)
            branches="$branches $(git branch --merged development | grep -v development)"
                 
                 
            git branch --merged main | grep -v main | xargs -n 1 git branch -d
            git branch --merged develop | grep -v develop | xargs -n 1 git branch -d
            git branch -vv | grep ': gone]' | grep -v 'develop' | grep -v 'main' | awk '{print $1}' | xargs -n 1 git branch -d
            git branch -vv | grep ': gone]' | grep -v 'develop' | grep -v 'main' | awk '{print $1}' | xargs -n 1 git push origin --delete