name: Docker-CI
on:
  pull_request:
    branches: ["main"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t baler:latest . --file Dockerfile
      
    - name: Train
      run: |
        docker run \
        --mount type=bind,source=${PWD}/projects/,target=/baler-root/projects \
        --mount type=bind,source=${PWD}/data/,target=/baler-root/data \
        baler:latest \
        --project=firstProject \
        --mode=train
        
    - name: Compress
      run: |
        docker run \
        --mount type=bind,source=${PWD}/projects/,target=/baler-root/projects \
        --mount type=bind,source=${PWD}/data/,target=/baler-root/data \
        baler:latest \
        --project=firstProject \
        --mode=compress
        
    - name: Decompress
      run: |
        docker run \
        --mount type=bind,source=${PWD}/projects/,target=/baler-root/projects \
        --mount type=bind,source=${PWD}/data/,target=/baler-root/data \
        baler:latest \
        --project=firstProject \
        --mode=decompress
