name: Code-Quality

on: [pull_request, workflow_dispatch]

jobs:
  test_and_lint:    
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.8", "3.9", "3.10"]
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
      
    - name: "install poetry"
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.3.2
        
    - name: "install dependencies"
      run: poetry install
      
    - name: "set pyhton path"
      run: echo "PYTHONPATH=.:baler" >> $GITHUB_ENV
    - name: "run tests"
      run: poetry run pytest
      
    - name: "run black"
      uses: psf/black@stable
      with:
        options: "--check"
        src: "./baler"
